language: php
php:
  - 5.6
env:
  - TEST_SUITE=unit
before_install:
  - sudo apt-get update -qq
before_script:
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv rehash;
  - composer install --no-interaction --dev
script:
  - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then ./vendor/bin/phpunit tests/; fi"