<?php

/**
 * Copyright (c) 2015 DD Art Tomasz Duda
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

namespace PowerEcommerce\System;

use PowerEcommerce\Utils\DataGenerator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-20 at 14:10:53.
 *
 * @group System
 * @group Collection
 */
class CollectionTest extends BaseTest
{
    /**
     * @var Collection
     */
    protected $object;

    function testConstructorInvalidArgumentException()
    {
        $i = $j = 0;

        $test = function ($data) use (&$i) {
            try {
                new Collection($data);
            } catch (\InvalidArgumentException $e) {
                ++$i;
            }
            return 1;
        };

        $j += $test(DataGenerator::_object()->current());
        $j += $test(DataGenerator::_integer()->current());
        $j += $test(DataGenerator::_string()->current());
        $j += $test(DataGenerator::_boolean()->current());
        $j += $test(DataGenerator::_float()->current());
        $j += $test(DataGenerator::_null()->current());
        $j += $test(DataGenerator::_resource()->current());

        $this->assertEquals($j, $i);
    }

    function testSetValue()
    {
        $assert = function ($data) {
            $this->assertTrue($this->object->setValue($data) instanceof Collection);
        };
        foreach (DataGenerator::_array() as $data) $assert($data);
        foreach (self::_object() as $data) $assert($data);
    }

    function testSetValueInvalidArgumentException()
    {
        $i = $j = 0;

        $test = function ($data) use (&$i) {
            try {
                $this->object->setValue($data);
            } catch (\InvalidArgumentException $e) {
                ++$i;
            }
            return 1;
        };

        $j += $test(DataGenerator::_object()->current());
        $j += $test(DataGenerator::_integer()->current());
        $j += $test(DataGenerator::_string()->current());
        $j += $test(DataGenerator::_boolean()->current());
        $j += $test(DataGenerator::_float()->current());
        $j += $test(DataGenerator::_null()->current());
        $j += $test(DataGenerator::_resource()->current());

        $this->assertEquals($j, $i);
    }

    function testGetValue()
    {
        $assert = function ($data) {
            $this->assertTrue(is_array($this->object->setValue($data)->getValue()));
        };

        $this->assertTrue(is_array($this->object->getValue()));

        foreach (DataGenerator::_array(1000) as $data) $assert($data);
        foreach (self::_object() as $data) $assert($data);
    }

    function testCompare()
    {
        $assert = function ($data) {
            $this->assertTrue($this->object->setValue($data)->compare($data));
        };

        foreach (DataGenerator::_array() as $data) $assert($data);
        foreach (self::_object() as $data) $assert($data);

        foreach (self::_strict() as list($d1, $d2))
            $this->assertFalse($this->object->setValue([$d1])->compare([$d2]));
    }

    function testCompareNoStrict()
    {
        $assert = function ($data) {
            $this->assertTrue($this->object->setValue($data)->compare($data, false));
        };

        foreach (DataGenerator::_array() as $data) $assert($data);
        foreach (self::_object() as $data) $assert($data);

        foreach (self::_strict() as list($d1, $d2))
            $this->assertTrue($this->object->setValue([$d1])->compare([$d2], false));
    }

    function testConcat()
    {
        $assert = function ($data) {
            $tmp = DataGenerator::_array()->current();
            $this->assertSame(array_merge($data, $tmp), $this->object->setValue($data)->concat($tmp)->getValue());
        };
        foreach (DataGenerator::_array() as $data) $assert($data);
    }

    function testContains()
    {
        $assert = function ($data) {
            $this->assertTrue($this->object->setValue($data)->contains($data));
            !is_object($data) && $this->assertTrue($this->object->setValue($data)->contains(array_slice($data, 0, sizeof($data) > 1 ? sizeof($data) - 1 : 1)));
        };

        foreach (DataGenerator::_array() as $data) $assert($data);
        foreach (self::_object() as $data) $assert($data);

        foreach (self::_strict() as list($d1, $d2))
            $this->assertFalse($this->object->setValue([$d1])->contains([$d2]));
    }

    function testContainsNoStrict()
    {
        $assert = function ($data) {
            $this->assertTrue($this->object->setValue($data)->contains($data, false));
            !is_object($data) && $this->assertTrue($this->object->setValue($data)->contains(array_slice($data, 0, sizeof($data) > 1 ? sizeof($data) - 1 : 1), false));
        };

        foreach (DataGenerator::_array() as $data) $assert($data);
        foreach (self::_object() as $data) $assert($data);

        foreach (self::_strict() as list($d1, $d2))
            $this->assertTrue($this->object->setValue([$d1])->contains([$d2], false));
    }

    function testGetTypeCode()
    {
        $this->assertSame(TypeCode::COLLECTION, $this->object->getTypeCode());
    }

    function testJoin()
    {
        $assert = function ($data) {
            $tmp = (array)DataGenerator::_array()->current();
            $this->assertSame(array_merge([$data, $data], $tmp, $tmp), $this->object->setValue([$data, $data])->join([$tmp, $tmp])->getValue());
        };
        foreach (DataGenerator::_array() as $data) $assert($data);
    }

    function testSlice()
    {
        $assert = function ($data) {
            $max = sizeof($data);
            if ($max) {
                $start = $max - mt_rand(0, $max - 1);
                $end = mt_rand($start, $max);
            } else {
                $start = $max;
                $end = $max;
            }
            $this->assertSame(array_slice($data, $start, $end), $this->object->setValue($data)->slice($start, $end));
        };
        foreach (DataGenerator::_array() as $data) $assert($data);
    }

    function testTruncate()
    {
        $assert = function ($data) {
            $max = sizeof($data);
            if ($max) {
                $start = $max - mt_rand(0, $max - 1);
                $end = mt_rand($start, $max);
            } else {
                $start = $max;
                $end = $max;
            }

            $this->assertSame(array_slice($data, $start, $end), $this->object->setValue($data)->truncate($start, $end)->getValue());
            $this->assertSame([], $this->object->setValue($data)->truncate()->getValue());
        };
        foreach (DataGenerator::_array() as $data) $assert($data);
    }

    function testArrayAccess()
    {
        $assert = function ($data) {
            $this->object[$data] = $data;

            $this->assertSame($data, $this->object[$data]);
            $this->assertArrayHasKey($data, $this->object);

            unset($this->object[$data]);
            $this->assertArrayNotHasKey($data, $this->object);
        };

        foreach (DataGenerator::_string(1000) as $data) $assert($data);
        foreach (DataGenerator::_integer(1000) as $data) $assert($data);
    }

    function testIterator()
    {
        $assert = function ($data) {
            $this->object->setValue($data);

            foreach ($this->object as $key => $value) {
                $this->assertTrue($key === key($data));
                $this->assertTrue($value === current($data));
                next($data);
            }
        };
        foreach (DataGenerator::_array() as $data) $assert($data);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Collection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
